# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Letscountit api

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: edgedb/setup-edgedb@v1
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.6
    - name:
      run: |
        edgedb migrate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install --with dev
    - name: Lint with ruff
      run: |
        # Check if there are any linting errors
        poetry run ruff check
        # Check if there are any formatting errors
        poetry run ruff format
    - name: Test with pytest
      run: |
        poetry run pytest

  build:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t simcax/letscountit-api:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: docker push simcax/letscountit-api:${{ github.run_number }}
