# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Letscountit api

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: edgedb/setup-edgedb@v1
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.6
    - name:
      run: |
        edgedb migrate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install --with dev
    - name: Lint with ruff
      run: |
        # Check if there are any linting errors
        poetry run ruff check
        # Check if there are any formatting errors
        poetry run ruff format
    - name: Test with pytest
      run: |
        poetry run pytest

  build:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: simcax/letscountit-api:0.${{ github.run_number }}.0
